language: node_js
node_js:
  - "4.1"
sudo: required
dist: trusty
before_install:
  - export CHROME_BIN=google-chrome-stable
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
  - google-chrome-stable --version
  - java -version
  - sudo apt-get install default-jre
script:
  - npm run webdriver-manager-update
  - npm run build
  - npm run ci-test
  - npm run e2e-test
